### ISSUE TITLE
Support proper parsing of Multi-block frames

### ISSUE THREAD

**Issue by Sly-Hyphen** [andrea202511/ecang#4]
For ethercat networks with many devices a single packet can't hold all the PDO. Multiple packets are used to read write to the logical address space. The ENI file describes these packets in the "cyclic" section. Any particular PDO will only map to one of these packets but the output right now maps every PDO to every packet.

**Comment by andrea202511** [comment]
Hi,
I suppose the two problems that you noted may have the same origin.
The Ecang's core was born about a year ago, to help me to diagnose a specific problem in a small ethercat network (one master and six slaves) after wasting too much time to parse manually a lot of very long pcapng files. Once fixed the problem not to lose the written code, I encapsulated it in the Ecang project. For this (and other things) Ecang ignores many interesting features of ethercat, just doing only the things I needed a year ago.
For example Ecang (and me too!) ignores the case with PDO splitted into multiple frames ... all the ethercat networks I work with use only one frame for all PDO.
If you have an example pcapng / eni file showing this I can try to expand ecang to handle these features ... but I can't promise anything, the time I can use for ecang may not be enough ;)

**Comment by Sly-Hyphen** [comment]
I understand, thanks for your work to make ecang public, it's much appreciated. I've learned a lot about the way ethercat works and wxwidgets by your project. I think I understand what needs to happen for my application and I will publish a pull request or a fork if/when I get it working!
